routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

//****************** WEBSITE *********************//
Route::view('', 'website.index')->name('website.home');
Route::view('contact', 'website.contact')->name('website.contact');

//****************** CMS-ADMIN *******************//
Route::prefix('cms/admin/')->namespace('Auth')->group(function () {
    Route::get('login', 'AdminAuthController@showLoginView')->name('cms.admin.login_view');
    Route::post('login', 'AdminAuthController@login')->name('cms.admin.login');
    Route::view('blocked', 'cms.blocked')->name('cms.admin.blocked');

    Route::get('forgot-password', 'AdminAuthController@showForgetPassword')->name('cms.admin.forgot_password_view');
    Route::post('forgot-password', 'AdminAuthController@requestNewPassword')->name('cms.admin.forgot_password');
});

Route::prefix('cms/admin/')->namespace('CMS')->middleware('auth:admin,author')->group(function () {
    Route::get('', 'AdminDashboardController@dashboard')->name('cms.admin.dashboard');
});

Route::prefix('cms/admin')->namespace('CMS')->middleware('auth:admin')->group(function (){
    Route::resource('admins', 'AdminController');
    Route::resource('authors', 'AuthorController');
    Route::resource('categories', 'CategoryController');
    Route::resource('users', 'UserController');
    Route::resource('roles', 'RoleController');
    Route::resource('permissions', 'PermissionController');
    Route::resource('contact-requests', 'ContactRequestController');
});

Route::prefix('cms/admin/')->namespace('CMS')->middleware('auth:admin')->group(function () {
    Route::get('roles/{id}/edit-permissions', 'RoleController@editRolePermissions')->name('roles.edit-permissions');
    Route::post('roles/{id}/update-permissions', 'RoleController@updateRolePermissions')->name('roles.update-permissions');

    Route::get('{id}/edit-permissions', 'AdminController@editPermissions')->name('admins.edit-permissions');
    Route::post('{id}/update-permissions', 'AdminController@updatePermissions')->name('admins.update-permissions');
});

Route::prefix('cms/admin/')->namespace('CMS')->middleware('auth:admin')->group(function () {
    Route::get('categories/{id}/articles', 'CategoryController@showArticles')->name('category.articles');
    Route::get('categories/{id}/authors', 'CategoryController@showAuthors')->name('category.authors');

    Route::get('authors/{id}/articles', 'AuthorController@showArticles')->name('author.articles');
    Route::get('authors/{id}/categories', 'AuthorController@showCategories')->name('author.categories');
});

Route::prefix('cms/admin')->namespace('CMS')->middleware('auth:admin,author')->group(function (){
    Route::resource('articles', 'ArticleController');
});

Route::prefix('cms/admin/')->namespace('Auth')->middleware('auth:admin')->group(function () {
    Route::get('password/reset', 'AdminAuthController@showResetPasswordView')->name('cms.admin.password_reset_view');
    Route::post('password/reset', 'AdminAuthController@resetPassword')->name('cms.admin.password_reset');
    Route::get('logout', 'AdminAuthController@logout')->name('cms.admin.logout');
});

//****************** CMS-AUTHOR ******************//
Route::prefix('cms/author/')->namespace('Auth')->group(function () {
    Route::get('login', 'AuthorAuthController@showLoginView')->name('cms.author.login_view');
    Route::post('login', 'AuthorAuthController@login')->name('cms.author.login');
});

Route::prefix('cms/author/')->middleware('auth:author')->group(function () {
    Route::get('logout', 'Auth\AuthorAuthController@logout')->name('cms.author.logout');
});

//****************** TEMP ******************//
Route::get('mailable', function () {
    $student = App\Admin::where('email', 'momen.sisalem@gmail.com')->first();
    return new App\Mail\AdminPasswordReset($student, '123123');
});

Route::view('err','cms.blocked');

app/Author.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;

class Author extends Authenticatable
{
    //

    use HasRoles;

    protected $hidden = ['status','password','remember_token','created_at','updated_at'];

    public function categories()
    {
        return $this->belongsToMany(Category::class,AuthorCategory::class,'author_id','category_id');
    }

    public function articles()
    {
        return $this->hasMany(Article::class, 'author_id', 'id');
    }
}

app/Http/Controllers/CMS/AuthorController.php
<?php

namespace App\Http\Controllers\CMS;

use App\Article;
use App\Author;
use App\Category;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class AuthorController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        //
        $authors = Author::withCount('categories','articles')->paginate(10);
        return view('cms.admin.authors.index', ['authorsData' => $authors]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
        $categories = Category::where('status', 'Visible')->get();
        return view('cms.admin.authors.create', ['categories' => $categories]);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
        $request->validate([
            'name' => 'required|string|min:3|max:30',
            'email' => 'required|string|email|unique:authors',
            'mobile' => 'required|numeric|unique:authors',
            'age' => 'required|integer|min:16|max:100',
            'author_image' => 'required|image',
            'gender' => 'required|in:Male,Female',
            'account_status' => 'string',
            'category_id' => 'required|exists:categories,id|integer'
        ]);

        $author = new Author();
        $author->name = $request->get('name');
        $author->email = $request->get('email');
        $author->mobile = $request->get('mobile');
        $author->age = $request->get('age');
        $author->password = Hash::make('1234');

        $authorImage = $request->file('author_image');
        $imageName = now() . '_' . $request->get('name');
        $authorImage->move('images/authors', $imageName);
        $author->image = $imageName;

        $author->gender = $request->get('gender');
        $author->status = $request->get('account_status') == 'on' ? "Active" : "Blocked";
        $isSaved = $author->save();

        $author->categories()->sync([$request->get('category_id')]);

        if ($isSaved) {
            $author->assignRole('author');
            session()->flash('status', 'alert-success');
            session()->flash('message', 'Author created successfully');
        } else {
            session()->flash('status', 'alert-danger');
            session()->flash('message', 'Author create failed!');
        }
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     */
    public function edit($id)
    {
        //
        $author = Author::find($id);
        return view('cms.admin.authors.edit', ['author' => $author]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, $id)
    {
        //
        $request->request->add(['id' => $id]);
        $request->validate([
            'id' => 'required|exists:authors,id',
            'name' => 'required|string|min:3|max:30',
            'email' => 'required|string|email|unique:authors,email,' . $id,
            'mobile' => 'required|numeric|unique:authors,mobile,' . $id,
            'age' => 'required|integer|min:16|max:100',
            'author_image' => 'image',
            'gender' => 'required|in:Male,Female',
            'account_status' => 'string'
        ]);

        $author = Author::find($id);
        $author->name = $request->get('name');
        $author->email = $request->get('email');
        $author->mobile = $request->get('mobile');
        $author->age = $request->get('age');

        if ($request->hasFile('author_image')) {
            $authorImage = $request->file('author_image');
            $imageName = now() . '_' . $request->get('name');
            $authorImage->move('images/authors', $imageName);
            $author->image = $imageName;
        }

        $author->gender = $request->get('gender');
        $author->status = $request->get('account_status') == 'on' ? "Active" : "Blocked";
        $isSaved = $author->save();
        if ($isSaved) {
            session()->flash('status', 'alert-success');
            session()->flash('message', 'Author updated successfully');
        } else {
            session()->flash('status', 'alert-danger');
            session()->flash('message', 'Author update failed!');
        }
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy($id)
    {
        //
        $isDeleted = Author::destroy($id);
        if ($isDeleted) {
            return response()->json(['icon' => 'success', 'title' => 'Author deleted successfully']);
        } else {
            return response()->json(['icon' => 'error', 'title' => 'Author delete failed']);
        }
    }

    public function showArticles($id)
    {
        $articles = Author::findOrFail($id)->articles()->paginate(10);
        return view('cms.admin.articles.index', ['articles' => $articles]);
    }

    public function showCategories($id){
        $categories = Author::findOrFail($id)->categories()->paginate(10);
        return view('cms.admin.categories.index', ['categoriesData' => $categories]);
    }
}

app/Http/Controllers/CMS/CategoryController.php
<?php

namespace App\Http\Controllers\CMS;

use App\Category;
use App\Http\Controllers\Controller;
use App\Http\Controllers\ControllersService;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        if (ControllersService::checkPermission('read-categories', 'admin')) {
            $categories = Category::withCount(['articles', 'authors'])->paginate(5);
            return view('cms.admin.categories.index', ['categoriesData' => $categories]);
        }
        return view('cms.blocked');
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
        if (ControllersService::checkPermission('create-category', 'admin')) {
            return view('cms.admin.categories.create');
        }
        return view('cms.blocked');
    }

    /**
     * Store a newly created resource in storage.
     * @param Request $request
     */
    public function store(Request $request)
    {
        //
        if (ControllersService::checkPermission('create-category', 'admin')) {
            $request->validate([
                'name_en' => 'required|String|min:5|max:45',
                'name_ar' => 'required|String|min:5|max:45',
                'status' => 'string'
            ]);

            $category = new Category();
            $category->name_en = $request->get('name_en');
            $category->name_ar = $request->get('name_ar');
            $category->status = $request->get('status') == 'on' ? 'Visible' : 'InVisible';

            $isSaved = $category->save();
            if ($isSaved) {
                $request->session()->flash('status', 'alert-success');
                $request->session()->flash('message', 'Category created successfully');
            } else {
                $request->session()->flash('status', 'alert-danger');
                $request->session()->flash('message', 'Category create failed!');
            }
            return redirect()->back();
        }
        return view('cms.blocked');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    public function showArticles(Request $request, $id)
    {
        if (ControllersService::checkPermission('read-articles', 'admin')) {
            $articles = Category::findOrFail($id)->articles()->with(['category', 'author'])->paginate(10);
            return view('cms.admin.articles.index', ['articles' => $articles]);
        }
        return view('cms.blocked');
    }

    public function showAuthors($id)
    {
        if (ControllersService::checkPermission('read-authors', 'admin')) {
            $authors = Category::findOrFail($id)->authors()->paginate(10);
            return view('cms.admin.authors.index', ['authorsData' => $authors]);
        }
        return view('cms.blocked');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     */
    public function edit($id)
    {
        //
        if (ControllersService::checkPermission('update-category', 'admin')) {
            $category = Category::find($id);
            return view('cms.admin.categories.edit', ['categoryData' => $category]);
        }
        return view('cms.blocked');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if (ControllersService::checkPermission('update-category', 'admin')) {
            $request->request->add(['category_id' => $id]);
            $request->validate([
                'category_id' => 'required|exists:categories,id|integer',
                'name_en' => 'required|String|min:5|max:45',
                'name_ar' => 'required|String|min:5|max:45',
                'status' => 'string'
            ]);

            $category = Category::find($id);
            $category->name_en = $request->get('name_en');
            $category->name_ar = $request->get('name_ar');
            $category->status = $request->get('status') == 'on' ? 'Visible' : 'InVisible';
            $isUpdated = $category->save();
            if ($isUpdated) {
                return redirect()->route('categories.index');
            } else {
                echo "Category update failed";
            }
        }
        return view('cms.blocked');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     */
    public function destroy($id)
    {
        //
        if (ControllersService::checkPermission('delete-category', 'admin')) {
            $isDeleted = Category::destroy($id);
            if ($isDeleted) {
                return response()->json(['icon' => 'success', 'title' => 'Category deleted successfully']);
            } else {
                return response()->json(['icon' => 'error', 'title' => 'Category delete failed']);
            }
        }
        return view('cms.blocked');
    }
}

resources/views/cms/admin/authors/index.blade.php
@extends('cms.admin.parent')

@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Authors</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Authors</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">News CMS - Authors</h3>
                            <a href="{{route('authors.create')}}" class="btn btn-sm btn-info float-right">Create New
                                Author</a>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <table id="example2" class="table table-bordered table-hover">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>ID</th>
                                    <th>Image</th>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Mobile</th>
                                    <th>Age</th>
                                    <th>Articles</th>
                                    <th>Catgories</th>
                                    <th>Gender</th>
                                    <th>Status</th>
                                    <th>Create Date</th>
                                    <th>Updated Date</th>
                                    <th>Settings</th>
                                </tr>
                                </thead>
                                <tbody>
                                <span hidden>{{$count = 0}}</span>
                                @foreach($authorsData as $author)
                                    <tr>
                                        <td><span class="badge badge-info">{{++$count}}</span></td>
                                        <td>{{$author->id}}</td>
                                        <td>
                                            <img src="{{url('images/authors/'.$author->image)}}" width="50" height="50">
                                        </td>
                                        <td>{{$author->name}}</td>
                                        <td>{{$author->email}}</td>
                                        <td>{{$author->mobile}}</td>
                                        <td>{{$author->age}}</td>
                                        <td>
                                            <a class="btn btn-info btn-sm"
                                               href="{{route('author.articles',[$author->id])}}">
                                                <i class="fas fa-sticky-note">
                                                </i>
                                                ({{$author->articles_count}}) Article/s
                                            </a>
                                            <span class="badge badge-dark"></span>
                                        </td>
                                        <td>
                                            <a class="btn btn-info btn-sm"

                                               href="{{route('author.categories',[$author->id])}}">
                                                <i class="fas fa-sticky-note">
                                                </i>
                                                ({{$author->categories_count}}) Category/s
                                            </a>
                                            <span class="badge badge-dark"></span>
                                        </td>
                                        <td>{{$author->gender}}</td>
                                        <td>
                                            @if($author->status == 'Active')
                                                <span class="badge badge-success">{{$author->status}}</span>
                                            @else
                                                <span class="badge badge-danger">{{$author->status}}</span>
                                            @endif
                                        </td>
                                        <td>{{$author->created_at}}</td>
                                        <td>{{$author->updated_at}}</td>
                                        <td>
                                            <a href="#" onclick="confirmDelete(this, '{{$author->id}}')"
                                               class="btn btn-xs btn-danger" style="color: white;">Delete</a>
                                            <a href="{{route('authors.edit',[$author->id])}}"
                                               class="btn btn-xs btn-info" style="color: white;">Edit</a>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                                <tfoot>
                                <tr>
                                    <th>#</th>
                                    <th>ID</th>
                                    <th>Image</th>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Mobile</th>
                                    <th>Age</th>
                                    <th>Articles</th>
                                    <th>Catgories</th>
                                    <th>Gender</th>
                                    <th>Status</th>
                                    <th>Create Date</th>
                                    <th>Updated Date</th>
                                    <th>Settings</th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>
                        <div class="row">
                            <div>
                                {{$authorsData->render()}}
                            </div>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>
@endsection

@section('scripts')
    <!-- DataTables -->
    <script src="{{asset('cms/plugins/datatables/jquery.dataTables.js')}}"></script>
    <script src="{{asset('cms/plugins/datatables-bs4/js/dataTables.bootstrap4.js')}}"></script>

    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>

    <script>
        function confirmDelete(app, id) {
            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.value) {
                    deleteAuthor(app, id)
                }
            })
        }

        function deleteAuthor(app, id) {
            axios.delete('/cms/admin/authors/' + id)
                .then(function (response) {
                    // handle success (Status Code: 200)
                    console.log(response);
                    console.log(response.data);
                    showMessage(response.data);
                    app.closest('tr').remove();
                })
                .catch(function (error) {
                    // handle error (Status Code: 400)
                    console.log(error);
                    console.log(error.response.data);
                    showMessage(error.response.data);
                })
                .then(function () {
                    // always executed
                });
        }

        function showMessage(data) {
            Swal.fire({
                position: 'center',
                icon: data.icon,
                title: data.title,
                showConfirmButton: false,
                timer: 1500
            })
        }
    </script>
@endsection