routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

//****************** WEBSITE *********************//
Route::view('', 'website.index')->name('website.home');
Route::view('contact', 'website.contact')->name('website.contact');

//****************** CMS-ADMIN *******************//
Route::prefix('cms/admin/')->namespace('Auth')->group(function () {
    Route::get('login', 'AdminAuthController@showLoginView')->name('cms.admin.login_view');
    Route::post('login', 'AdminAuthController@login')->name('cms.admin.login');
    Route::view('blocked', 'cms.blocked')->name('cms.admin.blocked');

    Route::get('forgot-password', 'AdminAuthController@showForgetPassword')->name('cms.admin.forgot_password_view');
    Route::post('forgot-password', 'AdminAuthController@requestNewPassword')->name('cms.admin.forgot_password');
});

Route::prefix('cms/admin/')->namespace('CMS')->middleware('auth:admin,author')->group(function () {
    Route::get('', 'AdminDashboardController@dashboard')->name('cms.admin.dashboard');
});

Route::prefix('cms/admin')->namespace('CMS')->middleware('auth:admin')->group(function (){
    Route::resource('admins', 'AdminController');
    Route::resource('authors', 'AuthorController');
    Route::resource('categories', 'CategoryController');
    Route::resource('users', 'UserController');
    Route::resource('roles', 'RoleController');
    Route::resource('permissions', 'PermissionController');
    Route::resource('contact-requests', 'ContactRequestController');
});

Route::prefix('cms/admin/')->namespace('CMS')->middleware('auth:admin')->group(function () {
    Route::get('roles/{id}/edit-permissions', 'RoleController@editRolePermissions')->name('roles.edit-permissions');
    Route::post('roles/{id}/update-permissions', 'RoleController@updateRolePermissions')->name('roles.update-permissions');

    Route::get('{id}/edit-permissions', 'AdminController@editPermissions')->name('admins.edit-permissions');
    Route::post('{id}/update-permissions', 'AdminController@updatePermissions')->name('admins.update-permissions');
});

Route::prefix('cms/admin/')->namespace('CMS')->middleware('auth:admin')->group(function () {
    Route::get('categories/{id}/articles', 'CategoryController@showArticles')->name('category.articles');
    Route::get('categories/{id}/authors', 'CategoryController@showAuthors')->name('category.authors');

    Route::get('authors/{id}/articles', 'AuthorController@showArticles')->name('author.articles');
    Route::get('authors/{id}/categories', 'AuthorController@showCategories')->name('author.categories');
});

Route::prefix('cms/admin')->namespace('CMS')->middleware('auth:admin,author')->group(function (){
    Route::resource('articles', 'ArticleController');
});

Route::prefix('cms/admin/')->namespace('Auth')->middleware('auth:admin')->group(function () {
    Route::get('password/reset', 'AdminAuthController@showResetPasswordView')->name('cms.admin.password_reset_view');
    Route::post('password/reset', 'AdminAuthController@resetPassword')->name('cms.admin.password_reset');
    Route::get('logout', 'AdminAuthController@logout')->name('cms.admin.logout');
});

//****************** CMS-AUTHOR ******************//
Route::prefix('cms/author/')->namespace('Auth')->group(function () {
    Route::get('login', 'AuthorAuthController@showLoginView')->name('cms.author.login_view');
    Route::post('login', 'AuthorAuthController@login')->name('cms.author.login');
});

Route::prefix('cms/author/')->middleware('auth:author')->group(function () {
    Route::get('logout', 'Auth\AuthorAuthController@logout')->name('cms.author.logout');
});

//****************** TEMP ******************//
Route::get('mailable', function () {
    $student = App\Admin::where('email', 'momen.sisalem@gmail.com')->first();
    return new App\Mail\AdminPasswordReset($student, '123123');
});

Route::view('err','cms.blocked');

resources/views/cms/admin/admins/create.blade.php
@extends('cms.admin.parent')

@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>User - Create</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Create User</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <!-- left column -->
                    <div class="col-md-12">
                        <!-- general form elements -->
                        <div class="card card-primary">
                            <div class="card-header">
                                <h3 class="card-title">Create User</h3>
                            </div>
                            <!-- /.card-header -->
                            <!-- form start -->
                            <form role="form" method="post" id="create_admin_form">
                                @csrf
                                <div class="card-body">

                                    <div class="alert alert-danger" id="error_alert" role="alert" hidden>
                                        <ul id="error_messages_ul"></ul>
                                    </div>

                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Full Name</label>
                                        <input id="name" value="{{old('name')}}" type="text"
                                               class="form-control"
                                               placeholder="Enter name">
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputPassword1">Email</label>
                                        <input id="email" value="{{old('email')}}" type="email"
                                               class="form-control" placeholder="Enter email">
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputPassword1">Mobile</label>
                                        <input id="mobile" value="{{old('mobile')}}" type="tel"
                                               class="form-control" placeholder="Enter mobile">
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputPassword1">Age</label>
                                        <input id="age" value="{{old('age')}}" type="number"
                                               class="form-control" placeholder="Enter age">
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputPassword1">Gender</label>
                                        <div class="custom-control custom-radio">
                                            <input class="custom-control-input" type="radio" id="Male"
                                                   name="gender" value="Male"
                                                   @if(old('gender') == 'Male') checked @else checked @endif>
                                            <label for="Male" class="custom-control-label">Male</label>
                                        </div>
                                        <div class="custom-control custom-radio">
                                            <input class="custom-control-input" type="radio" id="Female"
                                                   name="gender" value="Female"
                                                   @if(old('gender') == 'Female') checked @endif>
                                            <label for="Female" class="custom-control-label">Female</label>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label>Account Status</label>
                                        <div class="custom-control custom-switch">
                                            <input type="checkbox" class="custom-control-input" name="account_status"
                                                   id="account_status"
                                                   @if((old('account_status')) == 'on') checked @endif>
                                            <label class="custom-control-label" for="account_status">Active</label>
                                        </div>
                                    </div>
                                </div>
                                <!-- /.card-body -->

                                <div class="card-footer">
                                    <button type="button" onclick="createAdmin()" class="btn btn-primary">Save</button>
                                </div>
                            </form>
                        </div>
                        <!-- /.card -->
                    </div>
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
@endsection

@section('scripts')

<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>

    <script>
        function createAdmin(){
            axios.post('/cms/admin/admins', {
                name: document.getElementById("name").value,
                email: document.getElementById("email").value,
                mobile: document.getElementById("mobile").value,
                age: document.getElementById("age").value,
                gender: document.querySelector('input[name="gender"]:checked').value,
                status: document.getElementById("account_status").checked == true ? "Active" : "Blocked",
            })
            .then(function (response) {
                clearAndHideErrors();
                clearForm();
                showMessage(response.data);
            })
            .catch(function (error) {
                if (error.response.data.errors !== undefined) {
                    showErrorMessages(error.response.data.errors);
                } else {
                    showMessage(error.response.data);
                }
            });
        }

        function showErrorMessages(errors) {
            document.getElementById('error_alert').hidden = false
            var errorMessagesUl = document.getElementById("error_messages_ul");
            errorMessagesUl.innerHTML = '';

            for (var key of Object.keys(errors)) {
                var newLI = document.createElement('li');
                newLI.appendChild(document.createTextNode(errors[key]));
                errorMessagesUl.appendChild(newLI);
            }
        }

        function clearAndHideErrors(){
            document.getElementById('error_alert').hidden = true
            var errorMessagesUl = document.getElementById("error_messages_ul");
            errorMessagesUl.innerHTML = '';
        }

        function clearForm(){
            document.getElementById("create_admin_form").reset();
        }

        function showMessage(data){
            Swal.fire({
                position: 'center',
                icon: data.icon,
                title: data.title,
                showConfirmButton: false,
                timer: 1500
            })
        }
    </script>
@endsection

resources/views/cms/admin/admins/edit-admin-permissions.blade.php
@extends('cms.admin.parent')

@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Student - {{$admin->name}}</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Roles</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">Notes System - Update Admin Permissions</h3>
                            <a href="#" onclick="updateAdminPermissions('{{$admin->id}}')" class="btn btn-sm btn-info float-right">Update
                                Permissions</a>
                        </div>
                        <!-- /.card-header -->

                        <div class="card-body">
                            <div class="alert alert-danger" id="error_alert" role="alert" hidden>
                                <ul id="error_messages_ul"></ul>
                            </div>
                            <div class="col-md-8">
                                <label>Student: {{$admin->name}}</label>
                            </div>
                        </div>
                        <div class="card-body">
                            <table id="example2" class="table table-bordered table-hover">
                                <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Name</th>
                                    <th>Guard</th>
                                    <th>Status</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($permissions as $permission)
                                    <tr>
                                        <td>{{$permission->id}}</td>
                                        <td><span class="badge badge-info">{{$permission->name}}</span></td>
                                        <td>
                                            <span class="badge badge-primary">
                                                @if($permission->guard_name != '')
                                                    {{$permission->guard_name}}
                                                @else
                                                    -
                                                @endif
                                            </span>
                                        </td>
                                        <td>
                                            @if(count($adminPermissions) == 0)
                                                <div class="form-check">
                                                    <input type="checkbox" name="{{$permission->name}}"
                                                           class="form-check-input" id="{{$permission->id}}">
                                                    {{--                                                    <label class="form-check-label" for="exampleCheck1">Check me out</label>--}}
                                                </div>
                                            @else
                                                <div class="form-check">
                                                    <input type="checkbox" name="{{$permission->name}}"
                                                           class="form-check-input" id="{{$permission->id}}"
                                                           @foreach($adminPermissions as $adminPermission)
                                                           @if($adminPermission->id == $permission->id)
                                                           checked
                                                        @endif
                                                        @endforeach
                                                    >
                                                </div>
                                            @endif
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                                <tfoot>
                                <tr>
                                    <th>ID</th>
                                    <th>Title</th>
                                    <th>Guard</th>
                                    <th>Status</th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>
@endsection

@section('scripts')
    <!-- DataTables -->
    <script src="{{asset('cms/plugins/datatables/jquery.dataTables.js')}}"></script>
    <script src="{{asset('cms/plugins/datatables-bs4/js/dataTables.bootstrap4.js')}}"></script>
    <!-- Bootstrap Switch -->
    <script src="{{asset('cms/plugins/bootstrap-switch/js/bootstrap-switch.min.js')}}"></script>

    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>

    <script>
        var selectedPermissions = [];

        @if(count($adminPermissions) > 0)
        @foreach($adminPermissions as $adminPermission)

        selectedPermissions.push('{{$adminPermission->id}}');

        @endforeach
        @endif

        $('[type="checkbox"]').on('change', function () {
            var isChecked = $(this).is(":checked");
            if (isChecked) {
                selectedPermissions.push($(this).prop('id'));
                console.log('Checked: ' + $(this).prop('name'))
            } else {
                let itemId = $(this).prop('id');
                selectedPermissions = selectedPermissions.filter(function (item) {
                    return item !== itemId;
                });
                console.log('Un-Checked: ' + $(this).prop('name'))
            }
        });

        function updateAdminPermissions(id) {
            axios.post('/cms/admin/admins/' + id + '/update-permissions', {
                'permissions': selectedPermissions
            })
                .then(function (response) {
                    // handle success (Status Code: 200)
                    clearAndHideErrors();
                    showMessage(response.data);
                })
                .catch(function (error) {
                    // handle error (Status Code: 400)
                    if (error.response.data.errors !== undefined) {
                        showErrorMessages(error.response.data.errors);
                    } else {
                        showMessage(error.response.data);
                    }
                })
                .then(function () {
                    // always executed
                });
        }

        function showErrorMessages(errors) {
            document.getElementById('error_alert').hidden = false
            var errorMessagesUl = document.getElementById("error_messages_ul");
            errorMessagesUl.innerHTML = '';

            for (var key of Object.keys(errors)) {
                var newLI = document.createElement('li');
                newLI.appendChild(document.createTextNode(errors[key]));
                errorMessagesUl.appendChild(newLI);
            }
        }

        function clearAndHideErrors() {
            document.getElementById('error_alert').hidden = true;
            var errorMessagesUl = document.getElementById("error_messages_ul");
            errorMessagesUl.innerHTML = '';
        }

        function showMessage(data) {
            Swal.fire({
                position: 'center',
                icon: data.icon,
                title: data.title,
                showConfirmButton: false,
                timer: 1500
            })
        }
    </script>
@endsection

resources/views/cms/admin/admins/index.blade.php
@extends('cms.admin.parent')

@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Admins</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Admins</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">News CMS - Admins</h3>
                            @can('create-admin')
                                <a href="{{route('admins.create')}}" class="btn btn-sm btn-info float-right">Create New
                                    Admin</a>
                            @endcan
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <table id="example2" class="table table-bordered table-hover">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>ID</th>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Mobile</th>
                                    <th>Age</th>
                                    <th>Gender</th>
                                    <th>Status</th>
                                    <th>Permissions</th>
                                    <th>Create Date</th>
                                    <th>Updated Date</th>
                                    <th>Settings</th>
                                </tr>
                                </thead>
                                <tbody>
                                <span hidden>{{$count = 0}}</span>
                                @foreach($adminsData as $admin)
                                    <tr>
                                        <td><span class="badge badge-info">{{++$count}}</span></td>
                                        <td>{{$admin->id}}</td>
                                        <td>{{$admin->name}}</td>
                                        <td>{{$admin->email}}</td>
                                        <td>{{$admin->mobile}}</td>
                                        <td>{{$admin->age}}</td>
                                        <td>
                                            @if($admin->gender == 'Male')
                                                <span class="badge badge-info">{{$admin->gender}}</span>
                                            @else
                                                <span class="badge badge-warning">{{$admin->gender}}</span>
                                            @endif
                                        </td>
                                        <td>
                                            @if($admin->status == 'Active')
                                                <span class="badge badge-success">{{$admin->status}}</span>
                                            @else
                                                <span class="badge badge-danger">{{$admin->status}}</span>
                                            @endif
                                        </td>
                                        <td>
                                            <a class="btn btn-primary btn-sm"
                                               href="{{route('admins.edit-permissions',[$admin->id])}}">
                                                <i class="fas fa-sign">
                                                </i>
                                                Permission/s
                                            </a>
                                        </td>
                                        <td>{{$admin->created_at}}</td>
                                        <td>{{$admin->updated_at}}</td>
                                        <td>
                                            @if(auth()->user()->id != $admin->id)
                                                @can('delete-admin')
                                                    <a href="#" onclick="confirmDelete(this, '{{$admin->id}}')"
                                                       class="btn btn-xs btn-danger" style="color: white;">Delete</a>
                                                @endcan
                                            @endif
                                            @can('update-admin')
                                                <a href="{{route('admins.edit',[$admin->id])}}"
                                                   class="btn btn-xs btn-info" style="color: white;">Edit</a>
                                            @endcan
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                                <tfoot>
                                <tr>
                                    <th>#</th>
                                    <th>ID</th>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Mobile</th>
                                    <th>Age</th>
                                    <th>Gender</th>
                                    <th>Status</th>
                                    <th>Permissions</th>
                                    <th>Create Date</th>
                                    <th>Updated Date</th>
                                    <th>Settings</th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>
@endsection

@section('scripts')
    <!-- DataTables -->
    <script src="{{asset('cms/plugins/datatables/jquery.dataTables.js')}}"></script>
    <script src="{{asset('cms/plugins/datatables-bs4/js/dataTables.bootstrap4.js')}}"></script>

    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>

    <script>
        function confirmDelete(app, id) {
            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.value) {
                    deleteAdmin(app, id)
                }
            })
        }

        function deleteAdmin(app, id) {
            axios.delete('/cms/admin/admins/' + id)
                .then(function (response) {
                    // handle success (Status Code: 200)
                    console.log(response);
                    console.log(response.data);
                    showMessage(response.data);
                    app.closest('tr').remove();
                })
                .catch(function (error) {
                    // handle error (Status Code: 400)
                    console.log(error);
                    console.log(error.response.data);
                    showMessage(error.response.data);
                })
                .then(function () {
                    // always executed
                });
        }

        function showMessage(data) {
            Swal.fire({
                position: 'center',
                icon: data.icon,
                title: data.title,
                showConfirmButton: false,
                timer: 1500
            })
        }
    </script>
@endsection