routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

//****************** WEBSITE *********************//
Route::view('', 'website.index')->name('website.home');
Route::view('contact', 'website.contact')->name('website.contact');

//****************** CMS-ADMIN *******************//
Route::prefix('cms/admin/')->namespace('Auth')->group(function () {
    Route::get('login', 'AdminAuthController@showLoginView')->name('cms.admin.login_view');
    Route::post('login', 'AdminAuthController@login')->name('cms.admin.login');
    Route::view('blocked', 'cms.blocked')->name('cms.admin.blocked');

    Route::get('forgot-password', 'AdminAuthController@showForgetPassword')->name('cms.admin.forgot_password_view');
    Route::post('forgot-password', 'AdminAuthController@requestNewPassword')->name('cms.admin.forgot_password');
});

Route::prefix('cms/admin/')->namespace('CMS')->middleware('auth:admin,author')->group(function () {
    Route::get('', 'AdminDashboardController@dashboard')->name('cms.admin.dashboard');
});

Route::prefix('cms/admin')->namespace('CMS')->middleware('auth:admin')->group(function (){
    Route::resource('admins', 'AdminController');
    Route::resource('authors', 'AuthorController');
    Route::resource('categories', 'CategoryController');
    Route::resource('users', 'UserController');
    Route::resource('roles', 'RoleController');
    Route::resource('permissions', 'PermissionController');
    Route::resource('contact-requests', 'ContactRequestController');
});

Route::prefix('cms/admin/')->namespace('CMS')->middleware('auth:admin')->group(function () {
    Route::get('roles/{id}/edit-permissions', 'RoleController@editRolePermissions')->name('roles.edit-permissions');
    Route::post('roles/{id}/update-permissions', 'RoleController@updateRolePermissions')->name('roles.update-permissions');

    Route::get('{id}/edit-permissions', 'AdminController@editPermissions')->name('admins.edit-permissions');
    Route::post('{id}/update-permissions', 'AdminController@updatePermissions')->name('admins.update-permissions');
});

Route::prefix('cms/admin/')->namespace('CMS')->middleware('auth:admin')->group(function () {
    Route::get('categories/{id}/articles', 'CategoryController@showArticles')->name('category.articles');
    Route::get('categories/{id}/authors', 'CategoryController@showAuthors')->name('category.authors');

    Route::get('authors/{id}/articles', 'AuthorController@showArticles')->name('author.articles');
    Route::get('authors/{id}/categories', 'AuthorController@showCategories')->name('author.categories');
});

Route::prefix('cms/admin')->namespace('CMS')->middleware('auth:admin,author')->group(function (){
    Route::resource('articles', 'ArticleController');
});

Route::prefix('cms/admin/')->namespace('Auth')->middleware('auth:admin')->group(function () {
    Route::get('password/reset', 'AdminAuthController@showResetPasswordView')->name('cms.admin.password_reset_view');
    Route::post('password/reset', 'AdminAuthController@resetPassword')->name('cms.admin.password_reset');
    Route::get('logout', 'AdminAuthController@logout')->name('cms.admin.logout');
});

//****************** CMS-AUTHOR ******************//
Route::prefix('cms/author/')->namespace('Auth')->group(function () {
    Route::get('login', 'AuthorAuthController@showLoginView')->name('cms.author.login_view');
    Route::post('login', 'AuthorAuthController@login')->name('cms.author.login');
});

Route::prefix('cms/author/')->middleware('auth:author')->group(function () {
    Route::get('logout', 'Auth\AuthorAuthController@logout')->name('cms.author.logout');
});

//****************** TEMP ******************//
Route::get('mailable', function () {
    $student = App\Admin::where('email', 'momen.sisalem@gmail.com')->first();
    return new App\Mail\AdminPasswordReset($student, '123123');
});

Route::view('err','cms.blocked');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    //
    //protected $table = "categories_table";

    public function articles()
    {
        return $this->hasMany(Article::class, 'category_id', 'id');
    }

//    public function authors()
//    {
//        return $this->belongsToMany(Author::class, AuthorCategory::class, 'category_id', 'author_id');
//    }

    public function authors()
    {
        return $this->belongsToMany(Author::class, AuthorCategory::class, 'category_id', 'author_id');
    }
}

app/Http/Controllers/API/CategoryController.php
<?php

namespace App\Http\Controllers\API;

use App\Category;
use App\Http\Controllers\Controller;
use App\Http\Controllers\ControllersService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        //
        $categories = Category::where('status', 'Visible')->get();
        return response()->json([
            'status' => true,
            'message' => 'Success',
            'data' => $categories
        ]);
        //return ControllersService::generateArraySuccessResponse($categories,"Success");
    }

    public function showCategoryArticles(Request $request, $id)
    {
        $request->request->add(['id' => $id]);
        $roles = [
            'id' => 'required|exists:categories,id|integer',
        ];
        $validator = Validator::make($request->all(), $roles);
        if (!$validator->fails()) {
            $articles = Category::find($id)->articles()->with('author')->get();
            return ControllersService::generateArraySuccessResponse($articles, "Success");
        } else {
            return ControllersService::generateValidationErrorMessage($validator->getMessageBag()->first());
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $roles = [
            'name_en' => 'required|string|min:3',
            'name_ar' => 'required|string|min:3',
        ];
        $validator = Validator::make($request->all(), $roles);
        if (!$validator->fails()) {
            $category = new Category();
            $category->name_en = $request->get('name_en');
            $category->name_ar = $request->get('name_ar');
            $isSaved = $category->save();
            if ($isSaved) {
                return ControllersService::generateProcessResponse(true, 'CREATE_SUCCESS');
            }
        } else {
            return ControllersService::generateValidationErrorMessage($validator->getMessageBag()->first());
        }
    }
}

app/Http/Controllers/CMS/CategoryController.php
<?php

namespace App\Http\Controllers\CMS;

use App\Category;
use App\Http\Controllers\Controller;
use App\Http\Controllers\ControllersService;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        if (ControllersService::checkPermission('read-categories', 'admin')) {
            $categories = Category::withCount(['articles', 'authors'])->paginate(5);
            return view('cms.admin.categories.index', ['categoriesData' => $categories]);
        }
        return view('cms.blocked');
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
        if (ControllersService::checkPermission('create-category', 'admin')) {
            return view('cms.admin.categories.create');
        }
        return view('cms.blocked');
    }

    /**
     * Store a newly created resource in storage.
     * @param Request $request
     */
    public function store(Request $request)
    {
        //
        if (ControllersService::checkPermission('create-category', 'admin')) {
            $request->validate([
                'name_en' => 'required|String|min:5|max:45',
                'name_ar' => 'required|String|min:5|max:45',
                'status' => 'string'
            ]);

            $category = new Category();
            $category->name_en = $request->get('name_en');
            $category->name_ar = $request->get('name_ar');
            $category->status = $request->get('status') == 'on' ? 'Visible' : 'InVisible';

            $isSaved = $category->save();
            if ($isSaved) {
                $request->session()->flash('status', 'alert-success');
                $request->session()->flash('message', 'Category created successfully');
            } else {
                $request->session()->flash('status', 'alert-danger');
                $request->session()->flash('message', 'Category create failed!');
            }
            return redirect()->back();
        }
        return view('cms.blocked');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    public function showArticles(Request $request, $id)
    {
        if (ControllersService::checkPermission('read-articles', 'admin')) {
            $articles = Category::findOrFail($id)->articles()->with(['category', 'author'])->paginate(10);
            return view('cms.admin.articles.index', ['articles' => $articles]);
        }
        return view('cms.blocked');
    }

    public function showAuthors($id)
    {
        if (ControllersService::checkPermission('read-authors', 'admin')) {
            $authors = Category::findOrFail($id)->authors()->paginate(10);
            return view('cms.admin.authors.index', ['authorsData' => $authors]);
        }
        return view('cms.blocked');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     */
    public function edit($id)
    {
        //
        if (ControllersService::checkPermission('update-category', 'admin')) {
            $category = Category::find($id);
            return view('cms.admin.categories.edit', ['categoryData' => $category]);
        }
        return view('cms.blocked');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if (ControllersService::checkPermission('update-category', 'admin')) {
            $request->request->add(['category_id' => $id]);
            $request->validate([
                'category_id' => 'required|exists:categories,id|integer',
                'name_en' => 'required|String|min:5|max:45',
                'name_ar' => 'required|String|min:5|max:45',
                'status' => 'string'
            ]);

            $category = Category::find($id);
            $category->name_en = $request->get('name_en');
            $category->name_ar = $request->get('name_ar');
            $category->status = $request->get('status') == 'on' ? 'Visible' : 'InVisible';
            $isUpdated = $category->save();
            if ($isUpdated) {
                return redirect()->route('categories.index');
            } else {
                echo "Category update failed";
            }
        }
        return view('cms.blocked');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     */
    public function destroy($id)
    {
        //
        if (ControllersService::checkPermission('delete-category', 'admin')) {
            $isDeleted = Category::destroy($id);
            if ($isDeleted) {
                return response()->json(['icon' => 'success', 'title' => 'Category deleted successfully']);
            } else {
                return response()->json(['icon' => 'error', 'title' => 'Category delete failed']);
            }
        }
        return view('cms.blocked');
    }
}

resources/views/cms/admin/categories/create.blade.php
@extends('cms.admin.parent')

@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Category - Create</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Create Category</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <!-- left column -->
                    <div class="col-md-12">
                        <!-- general form elements -->
                        <div class="card card-primary">
                            <div class="card-header">
                                <h3 class="card-title">Create Category</h3>
                            </div>
                            <!-- /.card-header -->
                            <!-- form start -->
                            <form role="form" method="post" action="{{route('categories.store')}}">
                                @csrf

                                <div class="card-body">
                                    @if ($errors->any())
                                        <div class="alert alert-danger" role="alert">
                                            <ul>
                                                @foreach ($errors->all() as $error)
                                                    <li>{{ $error }}</li>
                                                @endforeach
                                            </ul>
                                        </div>
                                    @endif

                                    @if (session()->has('message'))
                                    <div class="alert {{session()->get('status')}} alert-dismissible fade show" role="alert">
                                        <span> {{ session()->get('message') }}<span>
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                          <span aria-hidden="true">&times;</span>
                                        </button>
                                      </div>
                                    @endif

                                    <div class="form-group">
                                        <label for="exampleInputEmail1">English Name</label>
                                        <input name="name_en" value="{{old('name_en')}}" type="text" class="form-control" id="exampleInputEmail1"
                                               placeholder="Enter english name">
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputPassword1">Arabic Name</label>
                                        <input name="name_ar" value="{{old('name_ar')}}" type="text" class="form-control"
                                               id="exampleInputPassword1" placeholder="Enter arabic name">
                                    </div>
                                    <div class="form-group">
                                        <div class="custom-control custom-switch">
                                            <input type="checkbox" name="status" class="custom-control-input"
                                             id="visibility_status" @if(old('status') == 'on') checked @endif>
                                            <label class="custom-control-label" for="visibility_status">Visibility
                                                Status</label>
                                        </div>
                                    </div>
                                </div>
                                <!-- /.card-body -->

                                <div class="card-footer">
                                    <button type="submit" class="btn btn-primary">Save</button>
                                </div>
                            </form>
                        </div>
                        <!-- /.card -->
                    </div>
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
@endsection

@section('scripts')

@endsection

resources/views/cms/admin/categories/edit.blade.php
@extends('cms.admin.parent')

@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Category - Update</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Update Category</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <!-- left column -->
                    <div class="col-md-12">
                        <!-- general form elements -->
                        <div class="card card-primary">
                            <div class="card-header">
                                <h3 class="card-title">Update Category</h3>
                            </div>
                            <!-- /.card-header -->
                            <!-- form start -->
                            <form role="form" method="post" action="{{route('categories.update',[$categoryData->id])}}">
                                @csrf
                                @method('PUT')
                                <div class="card-body">
                                    @if ($errors->any())
                                        <div class="alert alert-danger" role="alert">
                                            <ul>
                                                @foreach ($errors->all() as $error)
                                                    <li>{{ $error }}</li>
                                                @endforeach
                                            </ul>
                                        </div>
                                    @endif

                                    <div class="form-group">
                                        <label for="exampleInputEmail1">English Name</label>
                                        <input name="name_en" value="{{$categoryData->name_en}}" type="text" class="form-control" id="exampleInputEmail1"
                                               placeholder="Enter english name">
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputPassword1">Arabic Name</label>
                                        <input name="name_ar" value="{{$categoryData->name_ar}}" type="text" class="form-control"
                                               id="exampleInputPassword1" placeholder="Enter arabic name">
                                    </div>
                                    <div class="form-group">
                                        <div class="custom-control custom-switch">
                                            <input type="checkbox" name="status" @if($categoryData->status == 'Visible') checked @endif
                                             class="custom-control-input" id="visibility_status">
                                            <label class="custom-control-label" for="visibility_status">VisibilityStatus</label>
                                        </div>
                                    </div>
                                </div>
                                <!-- /.card-body -->

                                <div class="card-footer">
                                    <button type="submit" class="btn btn-primary">Update</button>
                                </div>
                            </form>
                        </div>
                        <!-- /.card -->
                    </div>
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
@endsection

@section('scripts')

@endsection

resources/views/cms/admin/categories/index.blade.php
@extends('cms.admin.parent')

@section('content')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Categories</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Categories</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">News CMS - Categories</h3>
                            @can('create-category')
                                <a href="{{route('categories.create')}}" class="btn btn-sm btn-info float-right">Create
                                    New
                                    Category</a>
                            @endcan
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <table id="example2" class="table table-bordered table-hover">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>ID</th>
                                    <th>Name (En)</th>
                                    <th>Name (Ar)</th>
                                    <th>Articles #</th>
                                    <th>Authors #</th>
                                    <th>Status</th>
                                    <th>Create Date</th>
                                    <th>Updated Date</th>
                                    <th>Settings</th>
                                </tr>
                                </thead>
                                <tbody>
                                <span hidden>{{$count = 0}}</span>
                                @foreach($categoriesData as $category)
                                    <tr>
                                        <td><span class="badge badge-info">{{++$count}}</span></td>
                                        <td>{{$category->id}}</td>
                                        <td>{{$category->name_en}}</td>
                                        <td>{{$category->name_ar}}</td>
                                        <td>
                                            <a class="btn btn-info btn-sm"
                                               href="{{route('category.articles',[$category->id])}}">
                                                <i class="fas fa-sticky-note">
                                                </i>
                                                ({{$category->articles_count}}) Article/s
                                            </a>
                                            <span class="badge badge-dark"></span>
                                        </td>
                                        <td>
                                            <a class="btn btn-info btn-sm"
                                               href="{{route('category.authors',[$category->id])}}">
                                                <i class="fas fa-sticky-note">
                                                </i>
                                                ({{$category->authors_count}}) Author/s
                                            </a>
                                            <span class="badge badge-dark"></span>
                                        </td>
                                        <td>
                                            @if($category->status == 'Visible')
                                                <span class="badge badge-success">{{$category->status}}</span>
                                            @else
                                                <span class="badge badge-danger">{{$category->status}}</span>
                                            @endif
                                        </td>
                                        <td>{{$category->created_at}}</td>
                                        <td>{{$category->updated_at}}</td>
                                        <td>
                                            @can('delete-category')
                                                <a href="#" onclick="confirmDelete(this, '{{$category->id}}')"
                                                   class="btn btn-xs btn-danger" style="color: white;">Delete</a>
                                            @endcan
                                            @can('update-category')
                                                <a href="{{route('categories.edit',[$category->id])}}"
                                                   class="btn btn-xs btn-info" style="color: white;">Edit</a>
                                            @endcan
                                        </td>

                                    </tr>
                                @endforeach
                                </tbody>
                                <tfoot>
                                <tr>
                                    <th>#</th>
                                    <th>ID</th>
                                    <th>Name (En)</th>
                                    <th>Name (Ar)</th>
                                    <th>Articles #</th>
                                    <th>Authors #</th>
                                    <th>Status</th>
                                    <th>Create Date</th>
                                    <th>Updated Date</th>
                                    <th>Settings</th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>
                        <div class="row justify-content-center">
                            {{$categoriesData->render()}}
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>
@endsection

@section('scripts')
    <!-- DataTables -->
    <script src="{{asset('cms/plugins/datatables/jquery.dataTables.js')}}"></script>
    <script src="{{asset('cms/plugins/datatables-bs4/js/dataTables.bootstrap4.js')}}"></script>

    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>

    <script>
        function confirmDelete(app, id) {
            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.value) {
                    deleteCategory(app, id)
                }
            })
        }

        function deleteCategory(app, id) {
            axios.delete('/cms/admin/categories/' + id)
                .then(function (response) {
                    // handle success (Status Code: 200)
                    console.log(response);
                    console.log(response.data);
                    showMessage(response.data);
                    app.closest('tr').remove();
                })
                .catch(function (error) {
                    // handle error (Status Code: 400)
                    console.log(error);
                    console.log(error.response.data);
                    showMessage(error.response.data);
                })
                .then(function () {
                    // always executed
                });
        }

        function showMessage(data) {
            Swal.fire({
                position: 'center',
                icon: data.icon,
                title: data.title,
                showConfirmButton: false,
                timer: 1500
            })
        }
    </script>
@endsection